const Router = require('express').Router
const announcementController = require('../controllers/announcement-controller')
const authController = require('../controllers/auth-controller')
const userController = require('../controllers/user-controller')
const vehicleController = require('../controllers/vehicle-controller')
const verify = require('../verifyToken')

const router = new Router()

router.post('/registration', authController.registration)
router.post('/login', authController.login)
router.post('/authme', verify, authController.authme)
router.put('/user/update', verify, userController.updateCompanyUser)
router.get('/refresh', authController.refresh)
router.post('/users', verify, userController.getAllCompanyUsers)
router.post('/fleet', verify, vehicleController.getAllCompanyFleet)
router.put('/fleet/service-history', verify, vehicleController.updateVehicleData)
router.get('/departments', userController.getListOfConstants("departments"))
router.get('/services', userController.getListOfConstants("services"))
router.get('/businessTypes', userController.getListOfConstants("businessTypes"))
router.get('/vehicleTypes', userController.getListOfConstants("vehicleTypes"))
router.get('/announcements', verify, announcementController.getAllAnnouncementsByCompany)
router.post('/announcement/create', verify, announcementController.createAnnouncement)
router.put('/announcement/update', verify, announcementController.updateAnnouncement)
router.delete('/announcement/remove', verify, announcementController.removeAnnouncement)

// router.post('/get-products', productController.getProducts)
// router.post('/purchase', verify, productController.buyProduct)
//router.get('/products-by-page', productController.getProductsByPage)
// router.get('/products/details', productController.getOneProduct)
// router.post('/products/search', productController.getSearchProducts)
//router.post('/products/search-by-page', productController.getSearchProductsByPage)
// router.post('/products/filter', productController.getAdvancedSearchProducts)
//router.post('/products/filter-by-page', productController.getAdvancedSearchProductsByPage)
// router.post('/products/delete', verify, productController.deleteProduct)
// router.post('/products/add', verify, productController.addProduct)
// router.put('/products/update', verify, productController.updateProduct)

module.exports = router